### ISSUE TITLE
Absolute links

### ISSUE THREAD

**Issue by cba85** [alsacreations/guidelines#2]
Je suis tombé sur le fichier readme.md au format raw et j'ai vu que vous utilisiez des urls absolues.
Github recommande d'utiliser les relatives urls : https://help.github.com/articles/relative-links-in-readmes/

Comme vous l'avez compris, cette issue est surtout un prétexte pour avoir un moyen original de vous dire à quel point c'est génial que vous ayez partagé vos guidelines !
Super intéressant et très utile !
👍

**Comment by blupdew** [comment]
Merci, c'est bien vu et tout à fait approprié, le fichier README.md a été adapté.
